{{- if .Values.dispatcher.enabled }}
{{- range $index, $market := .Values.markets }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-dispatcher-{{ $market.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: librenms-dispatcher-{{ $market.name }}
spec:
  replicas: {{ $.Values.dispatcher.replicaCount }}
  selector:
    matchLabels:
      app: librenms-dispatcher-{{ $market.name }}
  template:
    metadata:
      labels:
        app: librenms-dispatcher-{{ $market.name }}
    spec:
      containers:
        - name: dispatcher
          image: "{{ $.Values.dispatcher.image }}"
          env:
            - name: DB_HOST
              value: "{{ $.Values.dispatcher.env.DB_HOST }}"
            - name: DB_NAME
              value: "{{ $.Values.dispatcher.env.DB_NAME }}"
            - name: DB_USER
              value: "{{ $.Values.dispatcher.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ $.Values.dispatcher.env.DB_PASSWORD }}"
            - name: REDIS_HOST
              value: "{{ $.Values.dispatcher.env.REDIS_HOST }}"
            - name: REDIS_PORT
              value: "{{ $.Values.dispatcher.env.REDIS_PORT }}"
            - name: SIDECAR_DISPATCHER
              value: "1"
            - name: DISPATCHER_NODE_ID
              value: "{{ $market.name }}"
            - name: TZ
              value: "{{ $.Values.dispatcher.env.TZ }}"
            - name: LIBRENMS_BASE_URL
              value: "{{ $.Values.dispatcher.env.LIBRENMS_BASE_URL }}"
            - name: LIBRENMS_SNMP_COMMUNITY
              value: "{{ $.Values.dispatcher.env.LIBRENMS_SNMP_COMMUNITY }}"
            - name: LIBRENMS_WEATHERMAP
              value: "{{ $.Values.dispatcher.env.LIBRENMS_WEATHERMAP }}"
            - name: CACHE_DRIVER
              value: "{{ $.Values.dispatcher.env.CACHE_DRIVER }}"
            - name: SESSION_DRIVER
              value: "{{ $.Values.dispatcher.env.SESSION_DRIVER }}"
            - name: SESSION_SECURE_COOKIE
              value: "{{ $.Values.dispatcher.env.SESSION_SECURE_COOKIE }}"
          volumeMounts:
            - name: librenms-data
              mountPath: /data
      volumes:
        - name: librenms-data
          persistentVolumeClaim:
            claimName: {{ if $.Values.librenms.persistence.existingClaim }}{{ $.Values.librenms.persistence.existingClaim }}{{ else }}librenms-data{{ end }}
{{- end }}
{{- end }}