apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
  namespace: {{ .Release.Namespace }}
  labels:
    app: librenms
spec:
  replicas: {{ .Values.librenms.replicaCount }}
  selector:
    matchLabels:
      app: librenms
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
        - name: librenms
          image: "{{ .Values.librenms.image }}"
          ports:
            - containerPort: {{ .Values.librenms.service.port }}
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_USER
              value: {{ .Values.database.user }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password }}
          volumeMounts:
            - name: librenms-data
              mountPath: /opt/librenms
      volumes:
        - name: librenms-data
          persistentVolumeClaim:
            claimName: {{ if .Values.librenms.persistence.existingClaim }}{{ .Values.librenms.persistence.existingClaim }}{{ else }}librenms-data{{ end }}

