{{- if and .Values.librenms.persistence.enabled (eq .Values.librenms.persistence.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librenms-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: librenms
  annotations:
    {{- if .Values.librenms.persistence.retainOnDelete }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.librenms.persistence.size }}
  {{- if .Values.librenms.persistence.storageClass }}
  storageClassName: {{ .Values.librenms.persistence.storageClass }}
  {{- end }}
{{- end }}
