{{- if .Values.oxidized.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.oxidized.persistence.existingClaim | default "oxidized-data" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: oxidized
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.oxidized.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.oxidized.persistence.size }}
  {{- if .Values.oxidized.persistence.storageClass }}
  storageClassName: {{ .Values.oxidized.persistence.storageClass }}
  {{- end }}
{{- end }}
