apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app: mariadb
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
  selector:
    app: mariadb
