{{- if .Values.rrdcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rrdcached
  labels:
    app: rrdcached
    release: {{ .Release.Name }}
spec:
  selector:
    app: rrdcached
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 42217
    targetPort: 42217
  type: {{ .Values.rrdcached.service.type }}
{{- end }}
