apiVersion: v1
kind: Service
metadata:
  name: librenms
  namespace: {{ .Release.Namespace }}
  labels:
    app: librenms
spec:
  type: {{ .Values.librenms.service.type }}
  ports:
    - port: {{ .Values.librenms.service.port }}
      targetPort: {{ .Values.librenms.service.port }}
      protocol: TCP
  selector:
    app: librenms
