{{- if .Values.syslog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: syslog
  namespace: {{ $.Release.Namespace }}
  labels:
    app: syslog
spec:
  type: NodePort
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514       # External service port
      targetPort: 514 # Internal container port
      nodePort: 31514 # NodePort for TCP traffic
    - name: syslog-udp
      protocol: UDP
      port: 514       # External service port
      targetPort: 514 # Internal container port
      nodePort: 32514 # NodePort for UDP traffic
  selector:
    app: syslog
---
{{- end }}
