{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
