# General Configuration
namespace: librenms

# LibreNMS
librenms:
  image: librenms/librenms:latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
  persistence:
    enabled: true
    size: 100Gi
    storageClass: longhorn
    existingClaim: ""  # Specify the name of an existing PVC to reuse, leave blank to create a new one
    retainOnDelete: true
  env:
    DB_HOST: mariadb
    DB_NAME: librenms
    DB_USER: librenms
    DB_PASSWORD: secure_librenms_password
    REDIS_HOST: redis
    REDIS_PORT: 6379
    PUID: 1000
    PGID: 1000
    TZ: UTC
    SERVER_NAME: nms.example.com
    CACHE_DRIVER: redis
    SESSION_SECURE_COOKIE: true


# Database (MariaDB)
database:
  image: mariadb:10.5
  replicaCount: 1
  rootPassword: "secure_root_password"
  user: "librenms"
  password: "secure_librenms_password"
  name: "librenms"
  persistence:
    enabled: true
    size: 100Gi
    storageClass: longhorn
    existingClaim: ""  # Specify the name of an existing PVC to reuse, leave blank to create a new one
    retainOnDelete: true  # Set to true to retain PVC even if the Helm release is deleted
  service:
    type: ClusterIP # Internal access only
    port: 3306

# Cache (Redis)
redis:
  image: redis:7.2-alpine
  replicaCount: 1
  service:
    type: ClusterIP # Internal access only
    port: 6379
  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn
    existingClaim: ""  # Specify the name of an existing PVC to reuse, leave blank to create a new one
    retainOnDelete: true  # Set to true to retain PVC even if the Helm release is deleted

# Ingress
ingress:
  enabled: true
  hosts:
    - name: nms.example.com
      serviceName: librenms
      servicePort: 8000
    #- name: graylog.example.com
    #  serviceName: graylog
    #  servicePort: 9000
    #- name: oxidized.example.com
    #  serviceName: oxidized
    #  servicePort: 8888
  tlsSecret: librenms-tls
  cert: |-
    -----BEGIN CERTIFICATE-----
    YOUR_CERTIFICATE_CONTENT
    -----END CERTIFICATE-----
  key: |-
    -----BEGIN PRIVATE KEY-----
    YOUR_PRIVATE_KEY_CONTENT
    -----END PRIVATE KEY-----
