replicaCount: 1

image:
  repository: felddy/foundryvtt
  pullPolicy: IfNotPresent
  tag: "latest"

foundry:
  username: "admin"
  adminKey: "your-admin-key"
  password: "your-password"
  hostname: "your-hostname"
  cssTheme: "fantasy" # Options are foundry, fantasy, or scifi
  telemetry: false
  cacheEnabled: true  # Set to false if you don't want cache
  cacheSize: 5Gi      # Define the cache volume size
  cachePath: "/data/cache"  # Cache path within the persistent volume

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 30Gi
  cacheSize: 5Gi  # Cache volume size

ddbProxy:
  enabled: true  # Toggle whether the ddb-proxy container is deployed
  image: "ghcr.io/mrprimate/ddb-proxy"  # Replace with the correct image
  tag: "latest"
  port: 3000  # Port used by ddb-proxy