apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  labels:
    app: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
      - name: netbox
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "{{ .Values.db.host }}"
        - name: DB_PORT
          value: "{{ .Values.db.port }}"
        - name: DB_NAME
          value: "{{ .Values.db.name }}"
        - name: DB_USER
          value: "{{ .Values.db.user }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: netbox-db-secret
              key: password
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: ALLOWED_HOSTS
          value: "{{ .Values.allowedHosts }}"
        volumeMounts:
        - name: netbox-media
          mountPath: /opt/netbox/netbox/media
      volumes:
      - name: netbox-media
        persistentVolumeClaim:
          claimName: netbox-media-pvc
