apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-postgresql
  labels:
    app: netbox-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox-postgresql
  template:
    metadata:
      labels:
        app: netbox-postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.db.name }}"
        - name: POSTGRES_USER
          value: "{{ .Values.db.user }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: netbox-db-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: netbox-postgresql-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: netbox-postgresql-storage
        persistentVolumeClaim:
          claimName: netbox-postgresql-pvc