apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-redis
  labels:
    app: netbox-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbox-redis
  template:
    metadata:
      labels:
        app: netbox-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379