{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    app: netbox
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.ingress.tls.key | b64enc | quote }}
{{- end }}