apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.cacheSize }}"
  storageClassName: "{{ .Values.persistence.storageClass }}"