{{- if .Values.ddbProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ddb-proxy
  labels:
    app: ddb-proxy
spec:
  type: ClusterIP
  selector:
    app: ddb-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.ddbProxy.port }}  # Port for the service
      targetPort: {{ .Values.ddbProxy.port }}  # Port on the ddb-proxy container
{{- end }}