{{- if .Values.ddbProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ddb-proxy
  labels:
    app: ddb-proxy
spec:
  type: NodePort
  selector:
    app: ddb-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.ddbProxy.port }}  # The port that the service will expose
      targetPort: {{ .Values.ddbProxy.port }}  # The port on the ddb-proxy container
      nodePort: {{ .Values.ddbProxy.nodePort | default 32000 }}  # NodePort, you can specify a range or allow dynamic assignment
{{- end }}