apiVersion: v1
kind: Secret
metadata:
  name: foundry-vtt-secrets
type: Opaque
data:
  admin-key: {{ .Values.foundry.adminKey | b64enc | quote }}
  password: {{ .Values.foundry.password | b64enc | quote }}