apiVersion: v1
kind: Service
metadata:
  name: foundry-vtt-service
spec:
  type: NodePort
  selector:
    app: foundry-vtt
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000  # You can adjust this to fit your needs
